# Docker Compose para Monitoring (Prometheus + Grafana)
# Usar en conjunto con docker-compose.yml principal

services:
  # Prometheus - Time series database para métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: keycloak-prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - keycloak-network

  # Grafana - Visualización de métricas
  grafana:
    image: grafana/grafana:latest
    container_name: keycloak-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ../monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - keycloak-network

  # PostgreSQL Exporter (opcional) - Métricas de PostgreSQL
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: keycloak-postgres-exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://${KC_DB_USER}:${KC_DB_PASSWORD}@keycloak-postgres:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - keycloak-postgres
    networks:
      - keycloak-network

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  keycloak-network:
    external: true
